### ISSUE TITLE
Move to KafkaJS

### ISSUE THREAD

**Issue by jlandersen** [jlandersen/vscode-kafka#10]
Use KafkaJS as client instead of kafka-node

https://github.com/tulios/kafkajs/issues/647

**Comment by fbricon** [comment]
@jlandersen do you have any ETA on this or are you looking for some external contribution?

**Comment by jlandersen** [comment]
Hoping to get this one in this week! Almost there

**Comment by fbricon** [comment]
Cool, there's a bunch of interesting features that depend on it, happy to see it moving forward!
