### ISSUE TITLE
Wrong syntax highlighting for randomized keys 

### ISSUE THREAD

**Issue by fbricon** [jlandersen/vscode-kafka#101]
Key appears white, when it contains a mustache placeholder:

 <img width="289" alt="Screenshot 2021-01-27 at 15 14 16" src="https://user-images.githubusercontent.com/148698/106003376-70eda600-60b2-11eb-94b5-02febacc1908.png">

This is the expected look:

<img width="211" alt="Screenshot 2021-01-27 at 15 15 21" src="https://user-images.githubusercontent.com/148698/106003528-937fbf00-60b2-11eb-9b09-aa639cb83023.png">

**Comment by angelozerr** [comment]
It should be fixed with https://github.com/jlandersen/vscode-kafka/pull/98

**Comment by angelozerr** [comment]
Fixed with https://github.com/jlandersen/vscode-kafka/pull/98
