### ISSUE TITLE
Declare key/value format for CONSUMER in kafka file

### ISSUE THREAD

**Issue by angelozerr** [jlandersen/vscode-kafka#112]
Improve kafka file CONSUMER (when https://github.com/jlandersen/vscode-kafka/pull/98 will be merged)  to declare key/value deserializer:

 * key-format = none, long, int, etc
 * value-format= none, long, int, etc

Example:

```
CONSUMER consumer-group-id
topic: prices
value-format: long
```

In the future we could add avro schema.

**Comment by angelozerr** [comment]
I will create a PR once https://github.com/jlandersen/vscode-kafka/pull/116 will be merged

**Comment by fbricon** [comment]
From the [doc](https://github.com/jlandersen/vscode-kafka/blob/master/docs/Consuming.md#kafka-file):

The `CONSUMER` block defines:
 * `consumer group id` which is declared after CONSUMER *[required]*.
 * `topic`: the topic id *[required]*.
 * `from`: the offset from which the consumer group will start consuming messages from. Possible values are: `earliest`, `latest`, or an integer value. *[optional]*.
 * `partitions` [**EXPERIMENTAL option**] : the partition number(s), or a partitions range, or a combinaison of partitions ranges *[optional]*. eg:
    * 0
    * 0,1,2
    * 0-2
    * 0,2-3
 * `key-format` : [deserializer](#Deserializer) to use for the key *[optional]*.
 * `value-format` : [deserializer](#Deserializer) to use for the value *[optional]*.

#### Deserializer

Deserializer can have the following value:

   * `none`: no deserializer (ignores content).
   * `string`: similar deserializer to the Kafka Java client [org.apache.kafka.common.serialization.StringDeserializer](https://github.com/apache/kafka/blob/master/clients/src/main/java/org/apache/kafka/common/serialization/StringDeserializer.java) which currently only supports `UTF-8` encoding.
   * `double`: similar deserializer to the Kafka Java client [org.apache.kafka.common.serialization.DoubleDeserializer](https://github.com/apache/kafka/blob/master/clients/src/main/java/org/apache/kafka/common/serialization/DoubleDeserializer.java).
   * `float`: similar deserializer to the Kafka Java client [org.apache.kafka.common.serialization.FloatDeserializer](https://github.com/apache/kafka/blob/master/clients/src/main/java/org/apache/kafka/common/serialization/FloatDeserializer.java).
   * `integer`: similar deserializer to the Kafka Java client [org.apache.kafka.common.serialization.IntegerDeserializer](https://github.com/apache/kafka/blob/master/clients/src/main/java/org/apache/kafka/common/serialization/IntegerDeserializer.java).
   * `long`: similar deserializer to the Kafka Java client [org.apache.kafka.common.serialization.LongDeserializer](https://github.com/apache/kafka/blob/master/clients/src/main/java/org/apache/kafka/common/serialization/LongDeserializer.java).
   * `short`: similar deserializer to the Kafka Java client [org.apache.kafka.common.serialization.ShortDeserializer](https://github.com/apache/kafka/blob/master/clients/src/main/java/org/apache/kafka/common/serialization/ShortDeserializer.java).
