### ISSUE TITLE
Unable to Produce message to cloudkarafka 

### ISSUE THREAD

**Issue by rahgadda** [jlandersen/vscode-kafka#115]
Created a new version of **vscode-kafka** using GIT Action as described in the Readme.md
https://github.com/jlandersen/vscode-kafka/actions/runs/586374455

I am able to connect to cloudkarafka but unable to send message to the topic.
Getting message "Error: Not authorized to access topics: [Topic authorization failed]"

Please suggest.

![image](https://user-images.githubusercontent.com/13075415/108706064-1706c180-7534-11eb-8276-af114469eb44.png)

**Comment by fbricon** [comment]
Can you try with https://github.com/jlandersen/vscode-kafka/actions/runs/589280867?

**Comment by rahgadda** [comment]
Thanks, @fbricon .

It's working fine.

**Comment by fbricon** [comment]
The vsix generation was borked. Fixed with https://github.com/jlandersen/vscode-kafka/commit/189b58fea1e0c291b1b0c268b6c77e76c6cbe9a5.
