### ISSUE TITLE
Support multiple kafka clusters

### ISSUE THREAD

**Issue by copdips** [jlandersen/vscode-kafka#12]
hello,

It seems that current version only support single kafka cluster. Could you please add the support for multiple ?

**Comment by jlandersen** [comment]
Hi @copdips,

I am starting work on this now. I had hoped to get #10  in first, but it is still pending an updated release, so it will be postponed after all.

**Comment by jlandersen** [comment]
I just published 0.9.0 which supports multiple clusters. This is a bigger change and includes some workflow changes as well (such as selecting a cluster for certain actions, like producing and consuming).

I am closing this issue for now, but any feedback and suggestions for improvements is appreciated. I have some further plans for building out this even more (first on my list is to improve the adding/editing clusters with a better configuration window than input dialogs).

**Comment by copdips** [comment]
@jlandersen 

It works like a charm, and I'm wandering where you save the settings, I cannot find the multiclusters in VSCode user settings.

**Comment by jlandersen** [comment]
> @jlandersen 
> 
> 
> 
> It works like a charm, I can add multiple clusters from the extension GUI. 
> 
> And I'm wandering where you save this setting, I cannot find it in VSCode user settings.

Great! Clusters are saved using the VS Code Extension API (global storage).
You can see the implementation here:

https://github.com/jlandersen/vscode-kafka/blob/master/src/settings/clusters.ts

I might add the option to mix those with clusters specified in user or workspace settings, for use cases where one might let cluster settings go into source control. Just an idea at this time.
