### ISSUE TITLE
Stop showing the "Kafka producer log" output view all the time

### ISSUE THREAD

**Issue by fbricon** [jlandersen/vscode-kafka#134]
I find showing the "Kafka producer log" output view very irritating, every time I click on produce, after I closed the view the 1st time.
![Mar-17-2021 15-26-59](https://user-images.githubusercontent.com/148698/111483622-407ecb80-8735-11eb-877a-6b75ee46e5af.gif)

**Comment by angelozerr** [comment]
The output gives the capability to check produce is done. If you don't know that it exists this output, I think you will never show it.

I think we should improve doc in https://github.com/jlandersen/vscode-kafka/blob/master/docs/Producing.md#producing-messages by adding a screenshot after `Kafka Producer Log` to explain to the user what is the content of `Kafka Producer Log`

The https://github.com/jlandersen/vscode-kafka/issues/117 could fix this `check produce is done` if we display the produce launch state (Producing, Produced, etc in code lens)
