### ISSUE TITLE
[QUESTION] - producing JSON collection as message

### ISSUE THREAD

**Issue by dlarr** [jlandersen/vscode-kafka#14]
@jlandersen @joanrieu 
Is it possible to produces several messages corresponding to elements in JSON

Let's say my .kafka is this one : 

```
PRODUCER non-keyed-json
topic: A_TOPIC
{"id":1,"name":"#1"}
{"id":2,"name":"#2"}
{"id":3,"name":"#3"}
```

Is it possible to produce 3 messages / records ?

**Comment by jlandersen** [comment]
Hi,

This is currently not possible. Your record would contain a single value that is the string of three JSON objects.

**Comment by dlarr** [comment]
Hello and thank you for the answer.

It's too bad :( I hope you plan to make this evolution, because this plugin is really cool and easy to use.

Closing this issue.

**Comment by jlandersen** [comment]
Thanks for the kind words :-)
I might take another pass at the producer format in the near future and see what improvements could be made. If this seems like a general use case - never say never.
