### ISSUE TITLE
Expose command to add clusters programatically

### ISSUE THREAD

**Issue by fbricon** [jlandersen/vscode-kafka#182]
I'm working on a case in [vscode-rhoas](https://github.com/redhat-developer/vscode-rhoas/issues/1), where I need to be able to execute a command to create a remote Kafka cluster, and when it's ready, automatically configure the newly created cluster into VS Code.

Exposing a new `vscode-kafka.api.addcluster` command, taking a cluster object for argument, would be very helpful

**Comment by angelozerr** [comment]
Fixed with https://github.com/jlandersen/vscode-kafka/pull/189
