### ISSUE TITLE
Support self signed certificates

### ISSUE THREAD

**Issue by hguerrero** [jlandersen/vscode-kafka#185]
When connecting to cluster using TLS, the certificate might be a self-signed cert. 

Today we receive an error, but there is no documentation on how to configure the cert to validate it.

**Comment by angelozerr** [comment]
I think it's the same issue than https://github.com/jlandersen/vscode-kafka/issues/86

**Comment by chonbash** [comment]
I have same problem. At #86 I didn't find solution.

**Comment by hguerrero** [comment]
#86 still open and tries to address SASL_SSL, so I guess it should fix the usage of any TLS endpoint. However, I suggest using this issue to track the specifics of using self-signed certs within any TLS type of config.

**Comment by angelozerr** [comment]
> I have same problem. At #86 I didn't find solution.

Yes sure, it's just some discussion. The issue which implement the idea with certificate (and another configuration) is https://github.com/jlandersen/vscode-kafka/issues/88

But please note if you have the capability to write a vscode extension, you can contribute to vscode-kafka with your cluster configuration. You extension could create the proper kafka config with the proper certificate https://kafka.js.org/docs/configuration#ssl 

If you are interested to write your own vscode extension, please see the sample at https://github.com/angelozerr/vscode-kafka-extension-sample/blob/f3470cb0ab8777085e256571eeecc20fd77a7a83/src/extension.ts#L106

For the moment, there is no a robus documentation,please add comment in https://github.com/jlandersen/vscode-kafka/issues/129 if you need a documentation.
> However, I suggest using this issue to track the specifics of using self-signed certs within any TLS type of config.

Ok thanks for your suggestion.

**Comment by fbricon** [comment]
@hguerrero can you try the CI build from https://github.com/jlandersen/vscode-kafka/actions/runs/987534310 and give some feedback?

**Comment by angelozerr** [comment]
@hguerrero please note that there is a bug with ca, cert, key file save settings. Once you have selected the file, please add a space and remove a space on each file fields before saving. I'm fixing that.

**Comment by hguerrero** [comment]
Sure, I'll give it a try

**Comment by hguerrero** [comment]
Hey, @angelozerr what type of file do I need to get for the certificate authority? right now I tried, crt, pem, and keystore but I'm not able to select any using the `browse` button.

**Comment by angelozerr** [comment]
Its a mistake that i did. I need to add another file extensions. Please use the expected file extension for the moment by renaming your file extension. I will fix that soon

**Comment by hguerrero** [comment]
Ok, adding the full path in the textbox worked. 

Awesome work folks! 

I was able to connect with no trouble

![image](https://user-images.githubusercontent.com/1001939/124172155-7c853480-da77-11eb-9f3a-a84e1c790b18.png)

**Comment by fbricon** [comment]
@hguerrero was your certificate self-signed?

**Comment by hguerrero** [comment]
Yes, it was @fbricon

**Comment by fbricon** [comment]
Cool, thanks. FYI, @angelozerr has made some more improvements to the proposed changes, including fixing the file browsing. You can try a newer build from https://github.com/jlandersen/vscode-kafka/actions/runs/994037689

**Comment by hguerrero** [comment]
@fbricon I tested the new version, but unfortunately is not working.

Looks like when using the browse button:
- I can now select my file
- The file does not show in the textbox
- When I click on `Finish` the server is created but the cert is not linked

So, when trying to connect to my cluster I still get the self-signed cert error. 

If I add manually the path in the textbox, as I did with the previous version it works.

**Comment by fbricon** [comment]
@hguerrero what OS are you on?

**Comment by fbricon** [comment]
@hguerrero have you tried the latest build from https://github.com/jlandersen/vscode-kafka/actions/workflows/ci.yml?query=is%3Asuccess ?

**Comment by hguerrero** [comment]
> @hguerrero what OS are you on?

MacOS Big Sur v11.4

**Comment by hguerrero** [comment]
> @hguerrero have you tried the latest build from https://github.com/jlandersen/vscode-kafka/actions/workflows/ci.yml?query=is%3Asuccess ?

No, used the 6days old, let me try with the one from 1hr ago.

**Comment by hguerrero** [comment]
Ok,  I can confirm that the latest build (700) worked correctly.

**Comment by fbricon** [comment]
Fixed with #193

**Comment by kasperschnack** [comment]
Hi guys! First of all, thank you for making kafka available in vs code. I'm really looking forward to ditching the expensive conduktor I have to use through VNC. However I'm getting this error as well. I might have more than just this issue though - not sure:
1. I have this issue and I don't understand how I'm supposed to fix it
2. In conduktor I simply have to point to my truststore.jks file. I converted it using [this method](https://stackoverflow.com/a/656559). However this only creates a single PEM file. And I'm prompted for three different files in your setup:
![image](https://user-images.githubusercontent.com/8694416/149832173-59c50acd-ad2b-4d44-8dae-a234e856766a.png)

not really sure what that translates to. Any help would be greatly appreciated!

**Comment by angelozerr** [comment]
@kasperschnack to be honnest with you, I have none knowledge about JKS, etc. I have just consumed the kafkajs API and the expected tls ConnectionOptions :

https://github.com/jlandersen/vscode-kafka/blob/06b74ed03a57c73b2daec4a60a3dfd76145c039e/src/client/client.ts#L491

If it requires some changes, any feedback are welcome, thanks!

**Comment by IvanKostyuk** [comment]
Cannot connect using v0.15.0
Cannot find old build for v0.13.0

**Comment by IvanKostyuk** [comment]
The certificate I issued does not have correct hostnames, more than that, I'm playing with cluster of 3 brokers.
Need to have ability to bypass host validation.

Failed operation - Connection error: Hostname/IP does not match certificate's altnames: IP: <broker IP> is not in the cert's list

**Comment by fbricon** [comment]
To install a prior version:
<img width="906" alt="Screenshot 2022-07-29 at 09 14 28" src="https://user-images.githubusercontent.com/148698/181704206-ebde2a71-f4ec-4d58-bcea-d15692d87aa7.png">
<img width="870" alt="Screenshot 2022-07-29 at 09 14 45" src="https://user-images.githubusercontent.com/148698/181704211-79c97395-58c1-4a7a-a46f-cda1c516c573.png">
