### ISSUE TITLE
Add support for Kafka headers in the .kafka file

### ISSUE THREAD

**Issue by mscamargo** [jlandersen/vscode-kafka#199]
Hi there!

First of all, thanks for your great work! This is a very useful extension :smiley:

In the project I'm working on, we have to send metadata in kafka headers, but after some testing of the extension and some code reading, it seems that the extension doesn't support sending headers in kafka file. Are you considering this in the roadmap? It would be a great addition.

Thanks!

**Comment by angelozerr** [comment]
> First of all, thanks for your great work! This is a very useful extension 

Glad vscode-kafka can help you.

> In the project I'm working on, we have to send metadata in kafka headers, but after some testing of the extension and some code reading, it seems that the extension doesn't support sending headers in kafka file. 

Indeed it's not supported.

> Are you considering this in the roadmap? It would be a great addition.

The question is how to writ ethos hearders which is an array of key / value:

```
PRODUCER
headers: [
  {
    key: ....
    value: .....
  },
{
    key: ....
    value: .....
  }
]

```

@fbricon  @jlandersen  have you some idea?

**Comment by schadin** [comment]
Hello! 
My implementation #209

**Comment by angelozerr** [comment]
Fixed with https://github.com/jlandersen/vscode-kafka/pull/209
