### ISSUE TITLE
Failed to install 'jeppeandersen.vscode-kafka'.

### ISSUE THREAD

**Issue by simplymanas** [jlandersen/vscode-kafka#2]
Unable to install Extension 'jeppeandersen.vscode-kafka-0.5.2' as it is not compatible with Code '1.24.1'.

Not able to install this in mac, from the store.

Please ignore if the issue is fixed and I am unaware of this.

**Comment by jlandersen** [comment]
Hi @simplymanas 

There is a requirement in the extension for Code '1.30' (November 2018). 1.24 is from May 2018 so unfortunately the version is unsupported. Is there a specific reason for not being on the latest stable?

Thanks,
Jeppe

**Comment by simplymanas** [comment]
Thank you @jlandersen , I have updated to the latest one and it worked.
