### ISSUE TITLE
Make SSL optional when selecting SASL Auth

### ISSUE THREAD

**Issue by fbricon** [jlandersen/vscode-kafka#200]
We have a webview now (#193), but SSL is still required when selecting SASL* auth. 
@jnsjunior needs it to be optional (#195).

**Comment by angelozerr** [comment]
It means that we should just remove this validation https://github.com/jlandersen/vscode-kafka/blob/889a6068642cdeaf2bec40806abdd596beda1891/src/wizards/clusters.ts#L389 ?

**Comment by fbricon** [comment]
Changing the severity of the problem allows us to still warn the user and allow them to save the cluster

**Comment by fbricon** [comment]
@jnsjunior can you please check the CI build from https://github.com/jlandersen/vscode-kafka/actions/runs/1027031973?
