### ISSUE TITLE
Cluster Wizard fails loading assets ERR_ABORTED 404

### ISSUE THREAD

**Issue by rsmnarts** [jlandersen/vscode-kafka#211]
![image](https://user-images.githubusercontent.com/40693945/140659066-86a62225-e3d9-460a-b4a2-f8559ca0719d.png)
Does anyone know why the Kafka client in my vscode is like this?
If I check the developer tools, there are several error messages like in the picture

**Comment by angelozerr** [comment]
vscode-kafka uses https://github.com/redhat-developer/vscode-wizard to create a cluster with wizard and needs some loading of css, js. It seems that it misses those resources.

Your URL is very strange, me I have:

https://file+.vscode-resource.vscode-webview.net/c%3A/Users/azerr/.vscode/extensions/jeppeandersen.vscode-kafka-0.13.0/pages/shared/bootstrap/js/bootstrap.min.js

@fbricon have you some idea?

**Comment by fbricon** [comment]
I can reproduce the issue on my Mac. Probably caused by recent changes in VS Code

**Comment by fbricon** [comment]
Same problem on Ubuntu, but not on Windows 10. weird.

**Comment by angelozerr** [comment]
It's so bad -(

**Comment by angelozerr** [comment]
@robstryker did you encounter the same probem with last version of vscode and your vscode extensions which consumes vscode-wizard?

**Comment by angelozerr** [comment]
It seems HTML page can be loaded but not css, js etc. Perhaps I'm wrong but perhaps theproblem comes from https://github.com/redhat-developer/vscode-wizard/blob/563dd9657c892f731805dc3460caf4737cd94e2c/src/pageImpl.ts#L116 and vscode did some change in https://github.com/microsoft/vscode/issues/135361

I repeat me,it's perhaps a wrong suggestion. Just post that to try to understand the problem.

**Comment by Evynglais** [comment]
> Same problem on Ubuntu, but not on Windows 10. weird.

I've got this issue on Windows 10 as well as Ubuntu.
