### ISSUE TITLE
How to create .kafka file? Missing info in documentations

### ISSUE THREAD

**Issue by adakkj** [jlandersen/vscode-kafka#215]
Hi,
I would like to use .kafka file functionality, but I couldn't figure out how to use It. I suppose function "select cluster" should do this but in my case I dont have that kind of function. Is there a bug or I missing something?

Adam

**Comment by fbricon** [comment]
Just create a file with the .kafka extension: https://github.com/jlandersen/vscode-kafka/blob/master/docs/KafkaFile.md#kafkafile

Then you can create producers or consumers by typing `producer` or `consumer` in the file, a snippet will be injected in the file.
See https://github.com/jlandersen/vscode-kafka/blob/master/docs/Producing.md#producing and https://github.com/jlandersen/vscode-kafka/blob/master/docs/Consuming.md#kafka-file

**Comment by adakkj** [comment]
Adding right content to .kafka file helped. Snippet after that is visible and I can send messages! Thanks for your help:)
