### ISSUE TITLE
Add ability to remove a consumer

### ISSUE THREAD

**Issue by fbricon** [jlandersen/vscode-kafka#26]
From the Kafka explorer view, we should be able to select a consumer generated by vscode-kafka and remove it (it needs to be stopped before removing) 

See similar feature in conduktor:

![Dec-15-2020 11-06-19](https://user-images.githubusercontent.com/148698/102200933-c20c5680-3ec5-11eb-9dd7-4b808176bf4d.gif)

Removal fails if "the group is not empty"

**Comment by fbricon** [comment]
Ideally we could select multiple consumers and remove them in one action

**Comment by fbricon** [comment]
@jeppe do you plan on contributing this feature in the [next](https://github.com/jlandersen/vscode-kafka/milestone/1) release?

**Comment by angelozerr** [comment]
@fbricon I started something, I will create a draft PR soon.

**Comment by angelozerr** [comment]
> Ideally we could select multiple consumers and remove them in one action

I created an issue for that in https://github.com/jlandersen/vscode-kafka/issues/107 in other words my PR https://github.com/jlandersen/vscode-kafka/pull/106 support only a remove for a given consumer group.
