### ISSUE TITLE
Add support for SASL/SCRAM

### ISSUE THREAD

**Issue by winter98** [jlandersen/vscode-kafka#3]
Hi,

Do you intend to implement SASL_SSL (particularly SASL_SCRAM) connectivity ? 

Thanks.

**Comment by jlandersen** [comment]
Hi

I'd like to support SASL_SSL. The extension is based on https://github.com/SOHU-Co/kafka-node, which currently only supports the PLAIN mechanism. I am a contributor and could look into SCRAM when possible, but for now PLAIN is the more likely one to be supported. 
I'll see if I can get it in for next version in the next few weeks.

**Comment by winter98** [comment]
Would love SASL_SCRAM...

**Comment by winter98** [comment]
But thank you very much

**Comment by jlandersen** [comment]
@winter98 0.7.0 was just pushed which adds SASL/PLAIN. I'll keep this open and track of it and put in SCRAM when it becomes available in dependencies.

**Comment by rsun-thoughtworks** [comment]
Thanks, appreciate it.

**Comment by fbricon** [comment]
SASL/SCRAM should be doable (as well as OAUTHBEARER) once the extension uses kafkajs (see #10)  : https://kafka.js.org/docs/configuration#a-name-sasl-a-sasl

**Comment by fbricon** [comment]
@angelozerr if you want to test SASL/SCRAM auth, you can create a free account on https://www.cloudkarafka.com/plans.html

**Comment by fbricon** [comment]
I did a really quick'n dirty test to implement SASL/SCRAM 
<img width="717" alt="Screenshot 2021-01-05 at 18 40 26" src="https://user-images.githubusercontent.com/148698/103679737-837a3100-4f85-11eb-89e2-27f1bcac749a.png">

and it worked (tested against a https://www.cloudkarafka.com/ cluster) :
<img width="474" alt="Screenshot 2021-01-05 at 18 39 47" src="https://user-images.githubusercontent.com/148698/103679659-69d8e980-4f85-11eb-9b29-bbd62892b772.png">

Unfortunately, I can't seem to be able to produce records on that cloudkarafka topic (Error: Not authorized to access topics: [Topic authorization failed]). I don't know whether it's something I missed in my changes or if it's some sort of cluster limitation)

**Comment by fbricon** [comment]
Anyone interested in seeing SCRAM support, can test PR #67. 

Please [download](https://github.com/jlandersen/vscode-kafka/suites/1778964810/artifacts/33987808) the vscode-kafka 0.11.0 build for that PR and follow these [instructions](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to install the vsix file in vscode. Feedback is most welcome!
