### ISSUE TITLE
Consumer immediately closed after 1st start

### ISSUE THREAD

**Issue by fbricon** [jlandersen/vscode-kafka#58]
have a topic, start a consumer, view shows it started then stopped.

https://user-images.githubusercontent.com/148698/102693224-60c3ea80-4219-11eb-8fd8-67650d3e1ebd.mp4

Debugging shows it's caused by a call to [onDidCloseDocument](https://github.com/jlandersen/vscode-kafka/blob/master/src/providers/consumerVirtualTextDocumentProvider.ts#L16)
<img width="1056" alt="Screenshot 2020-12-19 at 16 45 47" src="https://user-images.githubusercontent.com/148698/102693281-c912cc00-4219-11eb-8d0c-901a871ba1f2.png">

This is most likely caused by https://github.com/jlandersen/vscode-kafka/pull/45/files#diff-20963d4437541e103325aa3a7abaef8fc29d762c2be8853b512bf74002ece3bdL84-L96

But why is onDidCloseDocument called when opening the document??

**Comment by jlandersen** [comment]
Seems to happen as a result of setting the language after creating the document:

https://code.visualstudio.com/api/references/vscode-api (no anchor link so copy pasting the important bit here):
```
onDidCloseTextDocument: Event<TextDocument>

An event that is emitted when a text document is disposed or when the language id of a text document has been changed.

(...)
```

Unfortunately it doesen't seem possible to create a new document with the language set unless the content is a simple string. I've added a check in the event handler to abort if the language is "plaintext" to work around this.

See: https://github.com/jlandersen/vscode-kafka/commit/cdb1f1bc8f73d27a877e3472738846fcc71424e3

**Comment by angelozerr** [comment]
It's very strange, most of the time,I had not this problem. Anyway thanks @jlandersen for the fix!
