### ISSUE TITLE
Config start offset in setting does not usable.

### ISSUE THREAD

**Issue by chrsas** [jlandersen/vscode-kafka#6]
I start a consumer to consume a topic, I have set the start offset earliest, but the consumer does not receive all messages.

**Comment by jlandersen** [comment]
Hi - couple of questions:

 - What version of Kafka re you using?
 - Are you activating consumer via explorer or the action menu?

**Comment by chrsas** [comment]
Kafka version 2.1
Via explorer

**Comment by jlandersen** [comment]
Thanks for the info - i'll get back when I have some news!

**Comment by jlandersen** [comment]
Better late than never (and Christmas holidays 🙏 ). I just published 0.8.2 which should fix this. Please let me know if it doesen't work as expected.
