### ISSUE TITLE
Improve selection of cluster

### ISSUE THREAD

**Issue by angelozerr** [jlandersen/vscode-kafka#62]
Cluster selection should be improved:

 * add documentation about the goal of cluster selection.
 * show in the kafka explorer which cluster is selcted
 * provide the Unselect command.

**Comment by fbricon** [comment]
> Cluster selection should be improved:
> 
> * add documentation about the goal of cluster selection.
OK
> * show in the kafka explorer which cluster is selcted
OK
> * provide the Unselect command.
why do you need an unselect command? Either you're using a cluster or your changing to another cluster

**Comment by fbricon** [comment]
See also https://github.com/jlandersen/vscode-kafka/issues/22

**Comment by angelozerr** [comment]
> why do you need an unselect command? Either you're using a cluster or your changing to another cluster

This command is just to give the capability to reset the selection state. For developer point view I think it's nice to have this command in order to test the current written code (which requires or not selection) with or without selection cluster.

**Comment by angelozerr** [comment]
> See also #22

I have seen this issue but I would prefer splitting features about cluster explorer in several issues (for review it will be more easy).
