### ISSUE TITLE
Elements should be sorted alphabetically in the explorer

### ISSUE THREAD

**Issue by fbricon** [jlandersen/vscode-kafka#63]
Clusters:
<img width="409" alt="Screenshot 2021-01-05 at 18 32 14" src="https://user-images.githubusercontent.com/148698/103678837-5d07c600-4f84-11eb-9428-917fc9023c71.png">

Consumers:
<img width="408" alt="Screenshot 2021-01-05 at 18 30 02" src="https://user-images.githubusercontent.com/148698/103678793-4a8d8c80-4f84-11eb-83ba-7083616c125a.png">

Topics look to be sorted alphabetically already:
<img width="398" alt="Screenshot 2021-01-05 at 18 34 35" src="https://user-images.githubusercontent.com/148698/103679082-b07a1400-4f84-11eb-808c-8fab313427a7.png">

**Comment by angelozerr** [comment]
I'm waiting for the merge of https://github.com/jlandersen/vscode-kafka/pull/72 to create a PR.
