### ISSUE TITLE
Check max for topic partitions

### ISSUE THREAD

**Issue by angelozerr** [jlandersen/vscode-kafka#65]
From https://github.com/jlandersen/vscode-kafka/pull/60#discussion_r551864012

We should prolly limit the max value for the number of topic partitions. Looks like 10 seems to be the max recommended amount, So setting [100](https://medium.com/swlh/choosing-right-partition-count-replication-factor-apache-kafka-cf50b1bc75cf) as a limit might be fine. @jlandersen WDYT?

Kafka clusters seem limited to [200K partions overall](https://blogs.apache.org/kafka/entry/apache-kafka-supports-more-partitions#:~:text=Apache%20Kafka%20Supports%20200K%20Partitions%20Per%20Cluster%20%3A%20Kafka), if anything that should be the hard limit.

**Comment by jlandersen** [comment]
cc @fbricon  as he mentioned it in the PR.

I think it's good with the validation of positive number for now. I don't think we should take as stand on what is an appropriate amount of partitions. I've worked with situations that made topics go from just a handful to a few hundred partitions for various reasons.  Going above any hard limit imposed by the cluster, I would assume would return an error for the request similar to setting an invalid replication factor in case you don't have enough brokers to honor and be handled/displayed automatically. I think it's good as-is.

**Comment by angelozerr** [comment]
Thanks @jlandersen for your feedback. 

@fbricon what do you think about that?

**Comment by angelozerr** [comment]
@fbricon I think we can close this issue, no?

**Comment by angelozerr** [comment]
I close the issue because it seems we should not manage this usecase https://github.com/jlandersen/vscode-kafka/issues/65#issuecomment-765996789
