### ISSUE TITLE
Randomize message key

### ISSUE THREAD

**Issue by fbricon** [jlandersen/vscode-kafka#66]
Currently, in producer files, only the message body goes through faker.js randomization. I was wondering whether we should allow similar filtering for message keys, eg. 
```json
PRODUCER keyed-message
topic: foo
key: customer-{{random.number}}
{
    "id": "{{random.uuid}}",
    "first_name": "{{name.firstName}}",
    "last_name": "{{name.lastName}}",
    "email": "{{internet.email}}",
    "country": "{{address.country}}"
}
```

@jlandersen does it make sense?

**Comment by jlandersen** [comment]
Good one - perhaps with support of using the same variables from the payload? I would say this is a pretty common case:

```
PRODUCER keyed-message
topic: foo
key: customer-{{random.uuid}} <- evaluates to same value as id property
{
    "id": "{{random.uuid}}",
    "first_name": "{{name.firstName}}",
    "last_name": "{{name.lastName}}",
    "email": "{{internet.email}}",
    "country": "{{address.country}}"
}
```

**Comment by fbricon** [comment]
`key: customer-{{id}}` is gonna be difficult to implement, but what I think is possible is to use the same [faker seed](https://github.com/marak/Faker.js/#setting-a-randomness-seed) for generating the key and the body, so that you can have 
```
key: customer-{{random.uuid}} // same value as id
{
    "id": "{{random.uuid}}",  // same value as in key
    "first_name": "{{name.firstName}}",
    "last_name": "{{name.lastName}}",
    "email": "{{internet.email}}",
    "country": "{{address.country}}"
}
```

I'll have to try

**Comment by fbricon** [comment]
Success!

<img width="1042" alt="Screenshot 2021-01-25 at 11 35 19" src="https://user-images.githubusercontent.com/148698/105694623-722ba100-5f01-11eb-8686-6b4707f1f2bc.png">

**Comment by jlandersen** [comment]
> Success!
> 
> <img alt="Screenshot 2021-01-25 at 11 35 19" width="1042" src="https://user-images.githubusercontent.com/148698/105694623-722ba100-5f01-11eb-8686-6b4707f1f2bc.png">

I know it was a bit of a stretch ;) nice one
