### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by mblandgithub** [jlandersen/vscode-kafka#71]
I downloaded the latest VS 2019 and when I download the vsix file it says there was an issue.  Log files shows extension is unsigned.  Any way around this?

**Comment by fbricon** [comment]
This extension works for visual studio code

**Comment by mblandgithub** [comment]
Not sure I understand your comments.  I downloaded and installed visual studio code and then trying to install this ext.  Not sure how to install it so that is why I asked the question.

**Comment by fbricon** [comment]
sorry I mistook your VS 2019 reference for Visual Studio 2019.

Have you tried installing from the extension view? https://code.visualstudio.com/docs/editor/extension-gallery#_browse-for-extensions

**Comment by mblandgithub** [comment]
I installed this
![image](https://user-images.githubusercontent.com/41790814/104042864-016a5200-51a9-11eb-896b-7acfad1ca32f.png)
 
When I goto ext with VS and search for KAFKA i see nothing.

When I goto the market place - https://marketplace.visualstudio.com/VSCode i see 

https://marketplace.visualstudio.com/items?itemName=jeppeandersen.vscode-kafka

I tried clicking install and nothing happens

I clicked download extenstion which download a vsix file and tried double clicking to run and i get this error.

![image](https://user-images.githubusercontent.com/41790814/104043294-9a00d200-51a9-11eb-8641-be5bc8e95abd.png)

Logs show
1/8/2021 12:03:51 PM - Microsoft VSIX Installer
1/8/2021 12:03:51 PM - -------------------------------------------
1/8/2021 12:03:51 PM - vsixinstaller.exe version:
1/8/2021 12:03:51 PM - 16.8.3036
1/8/2021 12:03:51 PM - -------------------------------------------
1/8/2021 12:03:51 PM - Command line parameters:
1/8/2021 12:03:51 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\MarkBland\Downloads\jeppeandersen.vscode-kafka-0.10.0(1).vsix
1/8/2021 12:03:51 PM - -------------------------------------------
1/8/2021 12:03:51 PM - Microsoft VSIX Installer
1/8/2021 12:03:51 PM - -------------------------------------------
1/8/2021 12:03:52 PM - Initializing Install...
1/8/2021 12:03:52 PM - Extension Details...
1/8/2021 12:03:52 PM - 	Identifier         : vscode-kafka
1/8/2021 12:03:52 PM - 	Name               : Kafka
1/8/2021 12:03:52 PM - 	Author             : jeppeandersen
1/8/2021 12:03:52 PM - 	Version            : 0.10.0
1/8/2021 12:03:52 PM - 	Description        : Interact with Kafka directly in VS Code
1/8/2021 12:03:52 PM - 	Locale             : en-US
1/8/2021 12:03:52 PM - 	MoreInfoURL        : 
1/8/2021 12:03:52 PM - 	InstalledByMSI     : False
1/8/2021 12:03:52 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
1/8/2021 12:03:52 PM - 
1/8/2021 12:03:52 PM - 	SignatureState     : Unsigned
1/8/2021 12:03:52 PM - 	Supported Products : 
1/8/2021 12:03:52 PM - 		Microsoft.VisualStudio.Code
1/8/2021 12:03:52 PM - 			Version : 
1/8/2021 12:03:52 PM - 
1/8/2021 12:03:52 PM - 	References         : 
1/8/2021 12:03:52 PM - Signature Details...
1/8/2021 12:03:52 PM - 	Extension is not signed.
1/8/2021 12:03:52 PM - 
1/8/2021 12:03:52 PM - Searching for applicable products...
1/8/2021 12:03:52 PM - Found installed product - Global Location
1/8/2021 12:03:52 PM - Found installed product - Visual Studio Community 2019
1/8/2021 12:03:52 PM - VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by mblandgithub** [comment]
Ok now after hyper focussing on the CODE word i found that I have installed VS with some CODE but not the VS CODE I should have.  I found this and wow the extension was so simple.  

Ignore this last comment 

Installed with ease.

Thanks for the help.
