### ISSUE TITLE
Basic SSL support

### ISSUE THREAD

**Issue by mike-england** [jlandersen/vscode-kafka#84]
Is it possible to attach to a kafka instance with SSL enabled?  For example, when I'm attaching to my cluster as a producer, I'll use the following:

KafkaProducer(bootstrap_servers=kafkaServer, security_protocol="SSL", ssl_check_hostname=True)

When attaching to the kafka cluster through this extension, I can specify the bootstrap server and port (443 in my case), but I can't seem to find a way to change the security protocol.

**Comment by fbricon** [comment]
Currently SSL is only enabled when using an authentication scheme, i.e. you have a username/password.
So you need SSL but no auth?

**Comment by mike-england** [comment]
Yes, currently we don't have any auth, just SSL.  I tried to specify SASL/Plain as authentication but with a blank username password, but that doesn't seem to work.

**Comment by fbricon** [comment]
Ok, so your use case seems quite simple but if we want to do SSL support right (and advertise we support SSL), we need to be able configure SSL certificate configuration, as per https://kafka.js.org/docs/configuration#ssl

Currently, the ssl boolean is only set here: https://github.com/jlandersen/vscode-kafka/blob/a0257d0932263cc66bce73c5579a9d530f9655b0/src/client/client.ts#L325

**Comment by mike-england** [comment]
Brilliant!  That works well for my purposes, it connects fine and seems to be working well.
