### ISSUE TITLE
Add support for SASL_SSL protocol

### ISSUE THREAD

**Issue by rmarting** [jlandersen/vscode-kafka#86]
Many clusters uses SASL_SSL protocolo (security.protocol) to autheticate the users.

It would be nice to allow it.

**Comment by fbricon** [comment]
Yeah it's what I refer to in https://github.com/jlandersen/vscode-kafka/issues/84#issuecomment-762821041

My understanding is, we need to provide a way to configure cluster certificates. I've thought of adding a few 3 more steps to the cluster config wizard (for CA, KEY and CERT), it should be easy to understand but I fear that'll make the config process pretty heavy.
Or we could let users configure a directory, and automatically pick up CA, KEY and CERT from there, but that requires documenting the discovery process and the naming scheme. 
Or we could point to a configuration file that lists the certificate files (but then we'd have to document how to write such file)
Or turn the whole wizard into a webview to list all the config in one page, but that goes against the spirit of vscode IMHO.

@jlandersen @angelozerr any ideas?

**Comment by angelozerr** [comment]
> Or turn the whole wizard into a webview to list all the config in one page, but that goes against the spirit of vscode IMHO.

I think if we want to follow the spirit of the vscode, cluster should be configure in settings.json and not in memento like today. vscode-sqltools follows this idea to configure connection.

**Comment by fbricon** [comment]
@angelozerr I *think* @jlandersen used vscode settings.json initially, but then moved to memento settings, for some reason

**Comment by fbricon** [comment]
Anyways, the memento vs settings.json debate is orthogonal to this discussion, this is an implementation detail. Right now I'm more concerned about the UI bits

**Comment by fbricon** [comment]
it'd be easy to review cluster config, once we enable #25

**Comment by angelozerr** [comment]
> Anyways, the memento vs settings.json debate is orthogonal to this discussion,

I would to say that with settings.json you can see the cluster configuration although memento hide this configuration. With settings.json you benefit with 

 * overview of the cluster config
 * edit cluster config (completion based on JSON schema)

But I agree settings.json doesn't provide advanced validation.

> this is an implementation detail. Right now I'm more concerned about the UI bits

As Kafka explorer looks like as Database explorer, I tried several vscode extension to manage connection configuration (which looks like cluster configuration) and each time they use a form with fields to configure connection configuration:

 * https://marketplace.visualstudio.com/items?itemName=bajdzis.vscode-database
 * https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools

Here a screenshot with SQLTools:

![image](https://user-images.githubusercontent.com/1932211/105313235-2655c080-5bbe-11eb-81f3-f01f083d0e6e.png)

I think we should have the same thing for cluster configuration. The form gives the capability to have an overview of the configuration and update fields.

If you like this idea, I can work on it.

**Comment by jlandersen** [comment]
I did move storage of clusters to memento as part of adding support for multiple clusters (https://github.com/jlandersen/vscode-kafka/commit/049dfa3083139102244b1fd7eb6ac04926263ce3). I'd like to revert to using settings, seeing as it is possible to update those values via. the workspace API.

I'm definitely in preference of using webview for managing clusters and allow selecting specific certificate files so definitely move ahead with that (also discussed in #88).

I've created #90 to discuss storage of clusters.

**Comment by fbricon** [comment]
@rmarting can you try the CI build from https://github.com/jlandersen/vscode-kafka/actions/runs/987534310 and give us some feedback?

**Comment by angelozerr** [comment]
@rmarting please note that there is a bug with ca, cert, key file save settings. Once you have selected the file, please add a space and remove a space on each file fields before saving. I'm fixing that.

**Comment by fbricon** [comment]
Fixed with #193

**Comment by rmarting** [comment]
@fbricon, @angelozerr I tested with some kafka clusters with SSL and SASL mechanisms successfully, however I found something that it is not working: I cannot choose the ca or key files from the browse button. 

When the file browser is opened the only files available are ca or key but the browser does not list me any file. In the folder my files are:

- CA: ca-dev.crt
- Key: ca-dev.key

However the browser does not list anything. I have to write in the text box the full path for both files, and saved. Then my connectios works but again in the browser button I cannot see the files.

My environment is:
- Fedora 33
- GNome 3.38.5
- File Browser: Nautilus

**Comment by angelozerr** [comment]
Have you tested with last build?

**Comment by rmarting** [comment]
Used the version provided here https://github.com/jlandersen/vscode-kafka/issues/86#issuecomment-872017089
Where could I download the latest one?

**Comment by fbricon** [comment]
@rmarting click on the latest run of https://github.com/jlandersen/vscode-kafka/actions/workflows/ci.yml then download and unzip the vscode-kafka archive

**Comment by rmarting** [comment]
Thanks @fbricon! With the latest one from there it is working successfully! So IMHO this version resolved this issue. Well done!
