### ISSUE TITLE
Language service for kafka file

### ISSUE THREAD

**Issue by angelozerr** [jlandersen/vscode-kafka#92]
It should be nice to provide a language service to provide relevant support for kafka files:

 * completion for topic
 * validation for topic
 * symbols for PRODUCER (and CONSUMER when it will be implemented)
 * folding range

The first thing to implement is a kafka file parser which maintains range location (the hard part, but as kafka file has a simple syntax it should not be a big deal).

Once we have this parser, it should be easy to implement completion, etc support. We could consume this language service directly in vscode or with a language server LSP (not sure it's interesting since kafka file are just consumed on vscode-kafka).

**Comment by fbricon** [comment]
Already implemented in 0.12.0
