### ISSUE TITLE
Start consumer with kafka file

### ISSUE THREAD

**Issue by angelozerr** [jlandersen/vscode-kafka#96]
Start consumer with configuration should be available inside kafka file:

```
CONSUMER test
topic: topic-a
partition: <number> (optional)
from: [earliest | latest | <offset>]
to: [latest | <offset>]
```

See https://github.com/jlandersen/vscode-kafka/issues/69#issuecomment-765894929

**Comment by angelozerr** [comment]
I can manage the from offset by using https://kafka.js.org/docs/consuming#a-name-seek-a-seek but KafkaJS doesn't provide to (offset).

If we cannot manage the to,perhaps CONSUMER should look like this:

```
CONSUMER test
topic: topic-a
partition: <number> (optional)
offset: [earliest | latest | <offset>]
```

@fbricon @jlandersen what do you think about  that?

**Comment by fbricon** [comment]
You can still call it `from`. The `to` can come later, whether the feature is implemented in kafka.js or here, we'll see

**Comment by angelozerr** [comment]
> You can still call it from. The to can come later, whether the feature is implemented in kafka.js or here, we'll see

Ok thanks for your feedback, I will do that.

I have an another question when you write 

`CONSUMER test`

what mean `test`? I suppose it's the name of the consumer to create ? 

Today this name is generated by using cluster, topic, from, position, my question what is the goal of this `test` name?

**Comment by fbricon** [comment]
This should be the consumer name, we should be able to use whatever we want, eg.:

<img width="409" alt="Screenshot 2021-01-27 at 16 15 04" src="https://user-images.githubusercontent.com/148698/106011706-042ad980-60bb-11eb-9383-16f0f0cabf97.png">

I imagine some clusters could be configured to enforce a certain consumer naming scheme, so being able to define the name in the CONSUMER attribute will be valuable.
